services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - .SearchFilmsSpring/src/main/resources/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres_data:/var/lib/postgresql/data

  app:
    build: SearchFilmsSpring
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - OMDB-API-KEY=${SPRING_API_KEY_OMDB}
    depends_on:
      - db

volumes:
  postgres_data: