spring.datasource.driverClassName= org.postgresql.Driver
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

omdb_api_key=${SPRING_API_KEY_OMDB}
omdb_api_url=${OMDB_API_URL}
frontend_angular_url=${FRONTEND_ANGULAR_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
